name: Actions Workflow

on:
  schedule:
    - cron: 0/5 * * * *
  push:
  pull-request:
    types: [open, closed, assigned, reopen]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout Action
        uses: actions/checkout@v1
      - name: List files after
        run: |
          pwd
          ls -a
      - name: Run JS Greet Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Aashu
      - name: Log Output
        run: echo "${{ steps.greet.outputs.time }}"

