name: ActionsWorkflow

on:
#  schedule:
#    - cron: 0/5 * * * *
  push:
    branches:
      - main
#      - 'feature/*'
#      - 'feature/**'
#      - '!feature/featA'
#    branches-ignore:  can't have both at the same time
#      - develop
#    tags:
#      - v1.*
#    paths-ignore:
#      - 'doc/**'
#    paths:
#      - '**.js'
#      - '!file1.js'
#  pull_request:
#    types: [open, closed, assigned, reopen]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout Action
        uses: actions/checkout@v1
      - name: List files after
        run: |
          pwd
          ls -a
      - name: Run JS Greet Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Aashu
      - name: Log Output
        run: echo "${{ steps.greet.outputs.time }}"
  call-reusable-workflow:
    needs: [run-github-actions]
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      VAR1: 'Variable String'
    secrets:
      TEST_SECRET: ${{secrets.TEST_SECRET}}
  upload-artifacts:
    uses: actions/upload-artifact@v3
    with:
      name: test
      path: src/test.txt
      retention-days: 5
  download-artifacts:
    needs: upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: test
      - name: Print file
        run: cat test.txt



