name: UseMatrix
on:
  repository_dispatch:
defaults:
  run:
    shell: bash
jobs:
  use-matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [10, 20, 30]
    steps:
      - name: Print matrx values
        run: echo ${{matrix.value}}
  print-dispatch-details:
    runs-on: ubuntu-latest
    steps:
      - name: Log details
        run: echo ${{github.event.client_payload.workflow}}
