name: Three
on:
  workflow_run:
    workflows: [Two]
    types: [completed]
    branches: [main]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: echo ${{github.event}}