name: Two
on:
  workflow_run:
    workflows: [One]
    types: [completed]
    branches: [main]
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: echo '${{ toJSON(github) }}'